### ISSUE TITLE
build fail

### ISSUE THREAD

**Issue by payliu** [centny/XEP#1]
hi~ sorry about building fail......

Projects/XEP/XEP/Library/NSLua.h:10:10: 'lua.h' file not found

**Comment by centny** [comment]
you must install lua library,see http://www.lua.org.

**Comment by payliu** [comment]
Yesterday, I tried fixed this issue for a while. I still can't fix it myself. Maybe problem is on environment setting or version of Lua library I used. I also found some config from project setting, such as /opt/local..., those configure are not on my computer. Maybe I need a Manual for help :sob:

**Comment by centny** [comment]
I just test it for newest lua 2.5.2. i fix the lua_objlen issue which lua 2.5.2 have removed.
if you want to build it,follow this:
1.download lua source
2.make macosx &make install
3.update the XEP source code and build it
note:if lua install directory is not /usr/local,update the Header Search Path,Library Search Path and Other Linker Flags in Xcode Setting.

**Comment by payliu** [comment]
Thanks, @Centny , you're very kind. I'll try it again. 
Do you know [Alcatraz](https://github.com/payliu/Alcatraz), this's a xcode plugins manager. If you are interesting in that, you can think about publish your plugins there, before this, you have to make XEP can be builded without any setting.

Actually, I tried to install XEP via Alcatraz yesterday, but fail to install. I'd like to know why, so then I tried to build XEP myself .....and then...you already know. :smile: 

[Alcatraz packages](https://github.com/payliu/alcatraz-packages)

**Comment by centny** [comment]
ok,i will try it when i am free.
