### ISSUE TITLE
how to  install to Xcode5 ? 

### ISSUE THREAD

**Issue by enefry** [centny/XEP#2]
I like this plug-in .

**Comment by enefry** [comment]
I add it into Xcode.app/Contents/PlugIns/
And  It work .

**Comment by centny** [comment]
already fix to xcode5,download XEP-v1.2.0.pkg file and install it.

**Comment by enefry** [comment]
Thanks

**Comment by centny** [comment]
i already adding the usage to github read me,https://github.com/Centny/XEP,

## 

Cny
Sent with Sparrow (http://www.sparrowmailapp.com/?sig)
