### ISSUE TITLE
force insert space into :: in c++ class method

### ISSUE THREAD

**Issue by enefry** [centny/XEP#5]
Nice:: Nice() {}

will Format to

Nice : : Nice() {}

how to change this config .

**Comment by yingguqing** [comment]
改配置文件应该就可以了，我是objectC，不同格式就是改配置文件。

发自我的 iPad

**Comment by enefry** [comment]
我就是问怎么改。 我用objective-c 用得很正常。但是c++的格式就不行了。
That is what i ask . I don't know how to change the config . objective-c work fine . 
Thanks.

```
改配置文件应该就可以了，我是objectC，不同格式就是改配置文件。

发自我的 iPad
```

**Comment by yingguqing** [comment]
~/library/Application
Support/Developer/Shared/Xcode/Plug-ins/XEP.dcplugin/Contents/Resources/uncrustify.cfg
find "# Add or remove space before the '::' operator " and "# Add or remove
space after the '::' operator"
set value with add

2014-03-29 15:17 GMT+08:00 陈 notifications@github.com:

**Comment by enefry** [comment]
I try it 

```

# Add or remove space before the '::' operator
sp_before_dc                             = add   # ignore/add/remove/force

# Add or remove space after the '::' operator
sp_after_dc                              = add   # ignore/add/remove/force
```

But it  still  insert a space between colon . 
void A : : done() {
    printf("Done");
}

**Comment by yingguqing** [comment]
sorry,I do not know how to do.

2014-03-29 15:55 GMT+08:00 ³Â notifications@github.com:
